<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SLNG.Assets</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibreMetaverse" Version="3.0.0" />
    <PackageReference Include="LibreMetaverse.Rendering.MeshFoundry" Version="3.0.0" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.14.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SLNG.Core\SLNG.Core.csproj" />
    <ProjectReference Include="..\SLNG.Net\SLNG.Net.csproj" />
  </ItemGroup>

</Project>
