<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SLNG.Assets</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SLNG.Core\SLNG.Core.csproj" />
  </ItemGroup>

</Project>
