version: '3.8'

services:
  opensim:
    image: soupbowl/opensimulator:0.9.3.0-screen
    container_name: slng-opensim
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
    environment:
      - ESTATE_NAME=SLNG Test Estate
      - ESTATE_OWNER_NAME=Test User
      - ESTATE_OWNER_PASSWORD=secret
      - REGION_NAME=SLNG Test Region
      - REGION_EXTERNAL_HOSTNAME=127.0.0.1
    volumes:
      - ./data:/opt/opensim/bin/sqlite-database
    restart: unless-stopped
