version: '3.8'

services:
  opensim:
    build: .
    container_name: slng-opensim
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
    volumes:
      - ./config/OpenSim.ini:/opensim/bin/OpenSim.ini:ro
      - ./config/Regions/Regions.ini:/opensim/bin/Regions/Regions.ini:ro
      - ./config/startup.txt:/opensim/bin/config/startup.txt:ro
    restart: unless-stopped
